main: Menu.o Table.o Restaurant.o Main.o
	clang++ -o main Menu.o Table.o Restaurant.o Main.o

Menu.o: Menu.cpp
	clang++ -c Menu.cpp

Table.o: Table.cpp
	clang++ -c Table.cpp

Restaurant.o: Restaurant.cpp
	clang++ -c Restaurant.cpp

Main.o: Main.cpp
	clang++ -c Main.cpp

